name: 'Apply'

on:
  push:
    branches: 
      - main
    paths:
      - 'terraform/**'
  workflow_dispatch:

jobs:
  terraform:
    name: 'apply'
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    runs-on: ubuntu-latest
    environment: apply

    defaults:
      run:
        shell: bash
        working-directory: 'terraform/'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      

      - name: Terraform Init
        id: init
        run: terraform init

    
      - name: Terraform Apply
        run: terraform apply --auto-approve