name: 'Destroy'

on:
    workflow_dispatch:
        inputs:
            dir:
                description: 'Directory with resources to be destroyed'
                required: true
                default: 'terraform'

jobs:
  terraform:
    name: 'destroy'
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    runs-on: ubuntu-latest
    environment: destroy

    defaults:
      run:
        shell: bash
        working-directory: 'terraform/'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      

      - name: Terraform Init
        id: init
        run: terraform init

    
      - name: Terraform Destroy
        run: terraform destroy --auto-approve